version: '3.6'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=simulador-banco
      - POSTGRES_USER=simulador-banco
      - POSTGRES_PASSWORD=123456789
      - MAX_CONNECTIONS=300